# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('national_average', models.DurationField()),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ShopWorkflowFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropoff', models.DateField()),
                ('pickup', models.DateField()),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='lengthofservice.Mechanic')),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lengthofservice.RepairType')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
